### ISSUE TITLE
EPIC: Users can submit reviews for Dining Commons Menu Items

### ISSUE THREAD

**Issue by ameymwalimbe** [ucsb-cs156/proj-dining#1]
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

User

### I can...

submit reviews for dining commons menu items

### So that...

share my thoughts and opinions about dining commons food

### Discussion

Users can log in and access their profile

- Can view all accepted reviews on their feed
- Can create, read, update, and delete their reviews

Through a create form, a student can submit their review which:
- Has an autogenerated `id`
- Has a dropdown for `diningCommonsName`
- Has a dropdown for `menuItemName`
- Has a dropdown for `stationName`
- Has a dropdown or slider for "number of stars" `rating` 
- Has a field for `comments`
- Has `submissionDate` (set based on when the student submits the reqest)
- Has `submit` button

### Acceptance Criteria

- [ ] As a user, I can login and see all accepted  reviews
- [ ] There are endpoints for each of the CRUD actions necessary to create, read, update, and delete a menu item review that have been tested on swagger
- GET `api/diningcommonsmenuitemreview?id={id}`
- PUT `api/diningcommonsmenuitemreview?id={id}`
- DELETE `api/diningcommonsmenuitemreview?id={id}`
- POST `api/diningcommonsmenuitemreview/post`

- [ ] A new dining commons menu item review can be created from create form (on the frontend) and is posted to the DiningCommonsMenuItem table.

- [ ] The dropdown fields for `diningCommonsName`, `stationName`, `menuItemName` are populated via the UCSB dining commons menu item API : ADD HERE

### Implementation Todos

F1: User Feed Page
- [ ] Add a new page to `frontend/src/main/pages` for the User Feed Page
- [ ] User Feed Page shows their reviews submitted in a table format, where they can also create a new review, edit existing reviews, delete reviews and see all approved reviews from themselves and other users (anonymized user names) 

F2 Create Review Page + Form Component 
- [ ] There is a button on the User Feed page to create a new request. This button leads to a page where the user can fill out a form for a new review.
- [ ] Form component is implemented in the frontend.
- [ ] Create Review Button is implemented and leads to a Create Review Page.
- [ ] Create Review Page has the form that can be filled out by the user.

B1: Create a DiningCommonsMenuItem Table :
- [ ] Create entity and repository files for a DiningCommonsMenuItem Request (`DiningCommonsMenuItemRequest.java`, `DiningCommonsMenuItemRequestRepository.java`)
- [ ] There is a database migration file: `DiningCommonsMenuItemRequest.json`
- [ ] Table is visible on H2 console and visible when tested on Dokku

B2: Implement CRUD operations for a DiningCommonsMenuItem Request
- [ ] Implement GET (show), PUT (edit), DELETE, and POST (create) endpoints (see above for endpoint suggestions)
- [ ] All the endpoints are implemented and tested in `DiningCommonsMenuItemRequestController.java` and `DiningCommonsMenuItemRequestControllerTests.java` and tested on Swagger and dokku-qa

B3: Populate dropdown fields for `diningCommonsName`, `stationName`, `menuItemName` via the UCSB dining commons menu item API
- [ ] ADD IMPLEMENTATION DETAILS HERE

- [ ] There is adequate test coverage for both the frontend and backend
