### ISSUE TITLE
EPIC: Users can see reviews of a particular menu item

### ISSUE THREAD

**Issue by Division7** [ucsb-cs156/proj-dining#6]
## User story

* As a user
* I can see reviews for an individual item
* So that I can decide what to pick

### Discussion

* Needs the menuItem table to exist
* Needs a backend endpoint that can retrieve reviews by menuItemId
* Needs to add to the 

### Acceptance Criteria

- [ ] As a user, when I navigate to the page I can see the reviews for a particular item
- [ ] There is a backend GET api endpoint at `api/diningcommonsmenuitemreview/{item}` that returns the reviews for a particular menu item

### Implementation Todos

F1: Frontend Issue name goes here
- [ ] Create a table component with the categories user alias, stars, and comments, and date
- [ ] There is a navigable page by menu item id that has the dining commons, the menu, the item name and the review for that particular item

B1: Backend Issue name goes here:
- [ ] There is a backend endpoint at `api/diningcommonsmenuitemreview/{item}` that returns the reviews for a particular item
